server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway9527.com
    prefer-ip-address: true 
 
zuul: 
  #ignored-services: microservicecloud-user
  ignored-services: "*"
  prefix: /hehui
  routes: 
    userService.serviceId: microservicecloud-user
    userService.path: /userService/**
 
info:
  app.name: hehui-microcloud
  company.name: www.lovehehui.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

